create sequence hibernate_sequence start 2 increment 1;
create table calculation (id int8 not null, address_object_constractions varchar(255), created_date timestamp, number int4, customer_id int8, results_id int8, сalculation_state_id int8, primary key (id));
create table customers (id int8 not null, address varchar(255) not null, email varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, phone int4 not null, second_name varchar(255) not null, primary key (id));
create table material_characteristics (id int8 not null, length float4, name varchar(255) not null, thickness float4, volume float4, width float4, measurement_unit_id int8, mаterials_id int8, primary key (id));
create table materials (id int8 not null, material_type varchar(255), name varchar(255) not null, structural_element_type varchar(255), primary key (id));
create table measurement_units (id int8 not null, measurement_units_name varchar(20) not null, primary key (id));
create table openings (id int8 not null, height float4, type varchar(255), width float4, primary key (id));
create table openings_in_a_structural_element_frame (id int8 not null, amount int4, structural_element_frame_id int8, primary key (id));
create table openings_in_a_structural_element_frame_openings_id (openings_in_a_structural_element_frame_id int8 not null, openings_id_id int8 not null);
create table price_lists (id int8 not null, date timestamp not null, purchase_price float4 not null, selling_price float4 not null, material_characteristics_id int8, primary key (id));
create table results (id int8 not null, amount int4, full_price float4, material varchar(255) not null, measurement_unit varchar(255), price float4, material_characteristics_id int8, primary key (id));
create table roles (id  serial not null, name varchar(20), primary key (id));
create table status (id int8 not null, name varchar(20), primary key (id));
create table structural_element_basement (id int8 not null, concrete varchar(255) not null, concrete_piles varchar(255) not null, internal_wall_length float4 not null, perimeter_of_external_walls float4 not null, results_id int8, primary key (id));
create table structural_element_frame (id int8 not null, osb_external_wall varchar(255) not null, osb_internal_wal varchar(255) not null, osb_thickness varchar(255) not null, amount_floor int4 not null, base_area float4 not null, external_wall_thickness float4 not null, floor_number int4 not null, insulation_external_wall varchar(255) not null, insulation_thickness varchar(255) not null, internal_wall_length float4 not null, internal_wall_thickness float4 not null, overlap_thickness varchar(255) not null, perimeter_of_external_walls float4 not null, steam_waterproofing_external_wall varchar(255) not null, steam_waterproofing_thickness varchar(255) not null, windscreen_external_wall varchar(255) not null, windscreen_thickness varchar(255) not null, results_id int8, primary key (id));
create table user_roles (user_id int8 not null, role_id int4 not null, primary key (user_id, role_id));
create table user_status (id int8 not null, name varchar(20), primary key (id));
create table users (id int8 not null, email varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, login varchar(255) not null, password varchar(255), phone varchar(255) not null, second_name varchar(255) not null, state_id int8, primary key (id));
create table users_customers_id (user_id int8 not null, customers_id_id int8 not null);
alter table openings_in_a_structural_element_frame_openings_id add constraint UK_gaiwdlq18djc02837jvv0crga unique (openings_id_id);
alter table users_customers_id add constraint UK_ekw68ydhuwe7b15dg30tl2gmd unique (customers_id_id);
alter table calculation add constraint FK4n7sgnxv9uwyun72xey3p0gf2 foreign key (customer_id) references customers;
alter table calculation add constraint FKegg8gfg8iexwgs0ajlo8dl9f foreign key (results_id) references results;
alter table calculation add constraint FKd5sau9vgxapu1lr0pgkbextfk foreign key (сalculation_state_id) references status;
alter table material_characteristics add constraint FK4c1iq63gc6vmu4as132fafn52 foreign key (measurement_unit_id) references measurement_units;
alter table material_characteristics add constraint FK32a9irc7s4dkr5214by29w463 foreign key (mаterials_id) references materials;
alter table openings_in_a_structural_element_frame add constraint FK2184y1gbd01nn9bwop7a7333q foreign key (structural_element_frame_id) references structural_element_frame;
alter table openings_in_a_structural_element_frame_openings_id add constraint FKpkpe3cm17uvoj52dhnimmr72d foreign key (openings_id_id) references openings;
alter table openings_in_a_structural_element_frame_openings_id add constraint FKq5pn00r4vxdl99q85ue3e7092 foreign key (openings_in_a_structural_element_frame_id) references openings_in_a_structural_element_frame;
alter table price_lists add constraint FK9d7t79dbn52h3l6wy6h2526s2 foreign key (material_characteristics_id) references material_characteristics;
alter table results add constraint FK8omqa8irx46djnftrncob0l0 foreign key (material_characteristics_id) references material_characteristics;
alter table structural_element_basement add constraint FKahteuynd44s517a4i4mx59wk4 foreign key (results_id) references results;
alter table structural_element_frame add constraint FKkmgqh3xt4h3mkrnluj02f6r0n foreign key (results_id) references results;
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table users add constraint FKaxe06byqbe517vwwoa2a8pv3f foreign key (state_id) references user_status;
alter table users_customers_id add constraint FKb4m94hafs5li4er9eun6bdsg2 foreign key (customers_id_id) references customers;
alter table users_customers_id add constraint FKcnol82jeu2dvaxj4pg5ksubmk foreign key (user_id) references users;